---
title: "P8105_HW5_ah4028"
author: "Austin Hsin"
date: "2023-11-14"
output: github_document
---

```{r setup, include=FALSE}
#Setup Code
library(tidyverse)
library(broom)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2

```{r study, message = FALSE}
file_names = list.files(path = "./data/study", full.names = TRUE) #list of all csv file names

study_import = function(path) { #creating function to import and tidy csv files
  
  df =
  read_csv(path) |>
    mutate(
      ID = path #creating ID variable from path name
    ) |>
    separate(ID, into = c("folder", "arm", "a", "subject", "csv"), sep = c(12, 16, 17, 19)) |> #separating ID into relevant sections
    arrange(arm, subject) |> #arranging by study arm and subject number
  pivot_longer(week_1:week_8,
               names_to = "Week",
               values_to = "Value") |> #pivoting original csv variables into `Week` and `Value`
     separate(Week, into = c("W", "Week_Num"), sep="_") |> #separating `Week` to obtain week number
    select(-folder, -a, -csv, -W) #removing non-pertinent variables
}

study_df_tidy = map(file_names, study_import) |>
  bind_rows() #merging all resulting files
```

```{r study_plot}
```